# Generated by Django 4.2 on 2024-07-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketmoney',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
