# Generated by Django 4.2 on 2024-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_bank_app', '0002_pocketmoney_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketmoney',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
