# Generated by Django 4.2 on 2024-07-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_bank_app', '0004_alter_pocketmoney_amount_jobcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='job_name',
            field=models.CharField(max_length=100),
        ),
    ]
