# Generated by Django 4.2 on 2024-07-28 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children_bank_app', '0006_jobcard_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('job_name', models.CharField(max_length=100)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
