# Generated by Django 4.2 on 2024-07-28 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children_bank_app', '0009_depositrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepositRequest',
            new_name='withdrawalRequest',
        ),
    ]
